"""
Export utilities for generating downloadable reports.
Supports Markdown, CSV, and JSON export formats.
"""

from __future__ import annotations

import csv
import io
import json
from datetime import datetime

from core.models import ReviewReport, ReviewComment


def export_markdown(report: ReviewReport) -> str:
    """
    Generate a formatted Markdown report.

    Args:
        report: The review report to export.

    Returns:
        Markdown string ready for download.
    """
    lines: list[str] = []

    # Header
    lines.append(f"# 🔍 AI Code Review Report")
    lines.append(f"")
    lines.append(f"**Repository:** [{report.repo_name}]({report.repo_url})")
    lines.append(f"**Reviewed:** {report.timestamp.strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Files analyzed:** {report.files_analyzed}")
    lines.append(f"**Total issues:** {report.total_comments}")
    lines.append(f"**Average confidence:** {report.avg_confidence:.1f}%")
    lines.append("")

    # Summary stats
    lines.append("## 📊 Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for severity in ["critical", "warning", "info", "suggestion"]:
        count = report.severity_distribution.get(severity, 0)
        emoji = {"critical": "🔴", "warning": "🟠", "info": "🔵", "suggestion": "🟢"}
        lines.append(f"| {emoji.get(severity, '')} {severity.capitalize()} | {count} |")
    lines.append("")

    # High confidence findings
    high = report.high_confidence_comments
    if high:
        lines.append("## ✅ High Confidence Findings")
        lines.append("")
        for c in high:
            lines.append(_format_comment_md(c))

    # Medium confidence
    medium = report.medium_confidence_comments
    if medium:
        lines.append("## 🟡 Medium Confidence Findings")
        lines.append("")
        for c in medium:
            lines.append(_format_comment_md(c))

    # Low confidence (needs verification)
    low = report.low_confidence_comments
    if low:
        lines.append("## ⚠️ Needs Verification (Low Confidence)")
        lines.append("")
        lines.append("> These findings have confidence scores below 50% and may require human review.")
        lines.append("")
        for c in low:
            lines.append(_format_comment_md(c, verify=True))

    # Footer
    lines.append("---")
    lines.append("*Generated by AI Code Review Agent — powered by Groq*")

    return "\n".join(lines)


def _format_comment_md(comment: ReviewComment, verify: bool = False) -> str:
    """Format a single comment as Markdown."""
    severity_badge = {
        "critical": "🔴 CRITICAL",
        "warning": "🟠 WARNING",
        "info": "🔵 INFO",
        "suggestion": "🟢 SUGGESTION",
    }

    lines = []
    badge = severity_badge.get(comment.severity, comment.severity.upper())
    verify_tag = " — ⚠️ *VERIFY THIS*" if verify else ""

    lines.append(f"### {badge}: {comment.title}{verify_tag}")
    lines.append(f"")
    lines.append(f"- **File:** `{comment.file_path}` (lines {comment.line_start}–{comment.line_end})")
    lines.append(f"- **Category:** {comment.category.replace('_', ' ').title()}")
    lines.append(f"- **Confidence:** {comment.confidence}%")
    lines.append(f"")
    lines.append(f"{comment.description}")
    lines.append(f"")

    if comment.suggestion:
        lines.append(f"**💡 Suggestion:** {comment.suggestion}")
        lines.append(f"")

    lines.append("---")
    lines.append("")
    return "\n".join(lines)


def export_csv(report: ReviewReport) -> str:
    """
    Generate a CSV export of all review comments.

    Args:
        report: The review report to export.

    Returns:
        CSV string ready for download.
    """
    output = io.StringIO()
    writer = csv.writer(output)

    # Header row
    writer.writerow([
        "File", "Line Start", "Line End", "Category", "Severity",
        "Title", "Description", "Suggestion", "Confidence",
        "Needs Verification",
    ])

    for c in report.comments:
        writer.writerow([
            c.file_path,
            c.line_start,
            c.line_end,
            c.category,
            c.severity,
            c.title,
            c.description,
            c.suggestion or "",
            c.confidence,
            "Yes" if c.needs_verification else "No",
        ])

    return output.getvalue()


def export_json(report: ReviewReport) -> str:
    """
    Generate a JSON export of the full report.

    Args:
        report: The review report to export.

    Returns:
        Pretty-printed JSON string.
    """
    data = {
        "repository": {
            "url": report.repo_url,
            "name": report.repo_name,
        },
        "metadata": {
            "timestamp": report.timestamp.isoformat(),
            "files_analyzed": report.files_analyzed,
            "files_skipped": report.files_skipped,
            "total_elements": report.total_elements,
            "total_comments": report.total_comments,
            "avg_confidence": report.avg_confidence,
        },
        "summary": report.summary_stats(),
        "comments": [
            {
                "file_path": c.file_path,
                "line_start": c.line_start,
                "line_end": c.line_end,
                "category": c.category,
                "severity": c.severity,
                "title": c.title,
                "description": c.description,
                "suggestion": c.suggestion,
                "confidence": c.confidence,
                "needs_verification": c.needs_verification,
                "confidence_bucket": c.confidence_bucket,
            }
            for c in report.comments
        ],
    }

    return json.dumps(data, indent=2, ensure_ascii=False)
