"""
Pydantic data models for the entire review pipeline.
Defines the structured schemas for AST-parsed code elements,
LLM review comments, and aggregated reports.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Literal

from pydantic import BaseModel, Field


# ── AST Parsing Models ────────────────────────────────────────────────────

class CodeElement(BaseModel):
    """A single AST-extracted code element (function, class, method, or import)."""

    name: str = Field(description="Name of the function, class, or imported module")
    element_type: Literal["function", "async_function", "class", "method", "import"] = Field(
        description="Type of code element"
    )
    code: str = Field(description="Raw source code of this element")
    line_start: int = Field(description="Starting line number (1-indexed)")
    line_end: int = Field(description="Ending line number (1-indexed)")
    docstring: str | None = Field(default=None, description="Docstring if present")
    complexity_hints: dict = Field(
        default_factory=dict,
        description="Hints about complexity: nesting_depth, arg_count, return_count, etc.",
    )


class FileAnalysis(BaseModel):
    """Complete AST analysis of a single source file."""

    file_path: str = Field(description="Relative path within the repository")
    language: str = Field(default="python", description="Programming language")
    elements: list[CodeElement] = Field(default_factory=list, description="Extracted code elements")
    raw_source: str = Field(description="Full raw source code of the file")
    loc: int = Field(description="Lines of code")
    imports: list[str] = Field(default_factory=list, description="List of import statements")
    parse_error: str | None = Field(
        default=None,
        description="Error message if the file could not be parsed",
    )


# ── LLM Review Models ─────────────────────────────────────────────────────

class ReviewComment(BaseModel):
    """A single review comment generated by the LLM."""

    file_path: str = Field(description="File this comment applies to")
    line_start: int = Field(description="Starting line of the issue")
    line_end: int = Field(description="Ending line of the issue")
    category: Literal[
        "bug_risk", "security", "performance",
        "style", "best_practice", "documentation", "error_handling",
    ] = Field(description="Category of the issue")
    severity: Literal["critical", "warning", "info", "suggestion"] = Field(
        description="Severity level"
    )
    title: str = Field(description="Short title summarizing the issue")
    description: str = Field(description="Detailed explanation of the issue")
    suggestion: str | None = Field(
        default=None,
        description="Suggested fix or improvement",
    )
    confidence: int = Field(
        ge=0, le=100,
        description="Confidence score 0-100%",
    )

    @property
    def needs_verification(self) -> bool:
        """Comments below 50% confidence should be flagged for human review."""
        return self.confidence < 50

    @property
    def confidence_bucket(self) -> str:
        """Return human-readable confidence bucket."""
        if self.confidence >= 70:
            return "high"
        elif self.confidence >= 50:
            return "medium"
        else:
            return "low"


class ReviewReport(BaseModel):
    """Aggregated review results for an entire repository."""

    repo_url: str = Field(description="GitHub URL of the reviewed repository")
    repo_name: str = Field(description="Repository name (owner/repo)")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="When the review was performed",
    )
    files_analyzed: int = Field(default=0, description="Number of files analyzed")
    files_skipped: int = Field(default=0, description="Number of files skipped")
    total_elements: int = Field(default=0, description="Total AST elements extracted")
    comments: list[ReviewComment] = Field(
        default_factory=list,
        description="All review comments",
    )

    @property
    def total_comments(self) -> int:
        return len(self.comments)

    @property
    def critical_count(self) -> int:
        return sum(1 for c in self.comments if c.severity == "critical")

    @property
    def high_confidence_comments(self) -> list[ReviewComment]:
        return [c for c in self.comments if c.confidence >= 70]

    @property
    def medium_confidence_comments(self) -> list[ReviewComment]:
        return [c for c in self.comments if 50 <= c.confidence < 70]

    @property
    def low_confidence_comments(self) -> list[ReviewComment]:
        return [c for c in self.comments if c.confidence < 50]

    @property
    def avg_confidence(self) -> float:
        if not self.comments:
            return 0.0
        return sum(c.confidence for c in self.comments) / len(self.comments)

    @property
    def category_distribution(self) -> dict[str, int]:
        dist: dict[str, int] = {}
        for c in self.comments:
            dist[c.category] = dist.get(c.category, 0) + 1
        return dist

    @property
    def severity_distribution(self) -> dict[str, int]:
        dist: dict[str, int] = {}
        for c in self.comments:
            dist[c.severity] = dist.get(c.severity, 0) + 1
        return dist

    def summary_stats(self) -> dict:
        """Generate summary statistics for the dashboard."""
        return {
            "files_analyzed": self.files_analyzed,
            "files_skipped": self.files_skipped,
            "total_elements": self.total_elements,
            "total_comments": self.total_comments,
            "critical_issues": self.critical_count,
            "avg_confidence": round(self.avg_confidence, 1),
            "categories": self.category_distribution,
            "severities": self.severity_distribution,
        }
